# Generated by Django 3.1.3 on 2020-11-22 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_Medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre medicamento')),
                ('Marca', models.CharField(max_length=100, verbose_name='Marca medicamento')),
                ('Laboratorio', models.CharField(max_length=100, verbose_name='Laboratorio medicamento')),
                ('Cantidad_de_comprimidos', models.IntegerField(verbose_name='Cantidad de comprimidos')),
                ('Gramaje', models.IntegerField(verbose_name='Gramaje')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Medicamento',
            fields=[
                ('id_Tipo_Medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Tipo_Medicamento', models.CharField(max_length=150, verbose_name='Nombre tipo medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Info_Medicamentos',
            fields=[
                ('id_Informacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medicamentos.medicamentos')),
                ('Formula', models.CharField(max_length=200, verbose_name='Formula')),
                ('Advertencias', models.CharField(max_length=250, verbose_name='Advertencias')),
                ('Indicaciones', models.CharField(max_length=250, verbose_name='Indicaciones')),
                ('Contra_Indicaciones', models.CharField(max_length=250, verbose_name='Contra indicaciones')),
                ('Bioequivalente', models.BooleanField(verbose_name='Bioequivalente')),
            ],
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='id_Tipo_medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.tipo_medicamento'),
        ),
    ]
