# Generated by Django 3.1.2 on 2020-11-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='Habilitado',
            field=models.BooleanField(default=True, verbose_name='Medicamento Habilitado'),
        ),
    ]
