# Generated by Django 3.1.3 on 2020-11-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_medicamentos_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_medicamentos',
            name='Bioequivalente',
            field=models.BooleanField(default=True, verbose_name='Bioequivalente'),
        ),
    ]
